---  # 2021 10 25

name: "Single Plugin Pipeline Dispatch"
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      - qa

jobs:
  single_plugin_pipeline_dispatch:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: "Prepare environment"
        run: |
          # Generate VARIABLES
          WORKFLOW_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          K8S_NAMESPACE="${{ github.ref }}"
          K8S_NAMESPACE="${K8S_NAMESPACE##*/}"
          HEAD_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          HEAD_COMMIT_MESSAGE=${HEAD_COMMIT_MESSAGE//[^a-zA-Z0-9_ .]/}

          SHA_SHORT=$(echo "${{ github.sha }}" | cut -c1-8)
          ISSUE_ID=$(echo "${{ github.event.head_commit.message }}" | grep -m1 -Po "LMSDEV-[0-9]*" || true)

          # Save them to ENV
          echo "WORKFLOW_URL=${WORKFLOW_URL}" | tee -a "${GITHUB_ENV}"
          echo "K8S_NAMESPACE=${K8S_NAMESPACE}" | tee -a "${GITHUB_ENV}"
          echo "HEAD_COMMIT_MESSAGE=${HEAD_COMMIT_MESSAGE}" | tee -a "${GITHUB_ENV}"
          echo "SHA_SHORT=${SHA_SHORT}" | tee -a "${GITHUB_ENV}"
          echo "ISSUE_ID=${ISSUE_ID}" | tee -a "${GITHUB_ENV}"

      - name: "Single Plugin Pipeline Dispatch"
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: Aprende-com/devops
          event-type: "single-plugin-pipeline-${{ env.K8S_NAMESPACE }}"
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "sha_short": "${{ env.SHA_SHORT }}",
              "workflow": "${{ github.workflow }}",
              "head_commit_message": "${{ env.HEAD_COMMIT_MESSAGE }}",
              "issue_id": "${{ env.ISSUE_ID }}",
              "run_id": "${{ github.run_id }}",
              "run_number": "${{ github.run_number }}",
              "actor": "${{ github.actor }}"
            }
